# Generated by Django 2.1.7 on 2019-02-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary')], default='P', max_length=1, verbose_name='Schedule Task Type'),
        ),
    ]
